package presentation;

import dao.*;
import daoMySQL.*;
import factory.*;
import javax.swing.*;
import java.awt.*;
import java.text.*;
import java.util.*;
import java.util.regex.*;
import transfertObject.*;

/**
 *
 * @author Philippe-K
 */

public class JDAjoutClient extends JDialog
{
    /**
     * Creates new form JDInsertClient
     */
    public JDAjoutClient(Frame parent, String titre)
    {
        super(parent, titre, true);
        initComponents();
        fillComponents();
        getRootPane().setDefaultButton(jButtonAdd);
        setLocation(parent.getX() + parent.getWidth() / 3, parent.getY() + parent.getHeight() / 3);
        setVisible(true);
    }
    
    private void fillComponents()
    {
        jComboBoxPays.removeAllItems();
        jComboBoxPays.addItem("*");
        ArrayList<Pays> listePays = daoPays.selectPays();
        for(int i = 0; i < listePays.size(); i++)
        {
            // Insertion des objets dans la comboBox,
            // Mais ils sont affichés grâce à leurs méthodes
            jComboBoxPays.addItem(listePays.get(i));
        }
        
        Date maDate = new Date();
        jDateChooserDDN.setDate(maDate);
    }
    
    private boolean verifText()
    {
        if(jTextFieldNom.getText().equals("") || jTextFieldPrénom.getText().equals("") 
           || jTextAreaAdresse.getText().equals("") || Integer.parseInt(jTextFieldCP.getText()) <= 0 
           || jTextFieldVille.getText().equals("") || jComboBoxPays.getSelectedIndex() == -1 || jDateChooserDDN.getDate() == null)
        {
            JOptionPane.showMessageDialog(null, "Un ou plusieurs champs est/sont vides!! Saisissez tous les champs s'il vous plaît!!", "Avertissement", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else
        {
            return true;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jLabelNewStudent = new javax.swing.JLabel();
        jLabelPrenom = new javax.swing.JLabel();
        jLabelNom = new javax.swing.JLabel();
        jLabelAdresse = new javax.swing.JLabel();
        jLabelCP = new javax.swing.JLabel();
        jLabelVille = new javax.swing.JLabel();
        jLabelPays = new javax.swing.JLabel();
        jTextFieldPrénom = new javax.swing.JTextField();
        jTextFieldNom = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAdresse = new javax.swing.JTextArea();
        jButtonAdd = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jTextFieldCP = new javax.swing.JTextField();
        jTextFieldVille = new javax.swing.JTextField();
        jComboBoxPays = new javax.swing.JComboBox();
        jLabelDDN = new javax.swing.JLabel();
        jDateChooserDDN = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelMain.setBackground(new java.awt.Color(153, 204, 255));

        jLabelNewStudent.setFont(new java.awt.Font("Cambria", 1, 28)); // NOI18N
        jLabelNewStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNewStudent.setText("   Ajouter un nouveau client");
        jLabelNewStudent.setFocusable(false);
        jLabelNewStudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelPrenom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPrenom.setText("Prénom :");

        jLabelNom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNom.setText("Nom :");

        jLabelAdresse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelAdresse.setText("Adresse :");

        jLabelCP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCP.setText("Code postal :");

        jLabelVille.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelVille.setText("Ville :");

        jLabelPays.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPays.setText("Pays :");

        jTextFieldPrénom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrénomKeyTyped(evt);
            }
        });

        jTextFieldNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomKeyTyped(evt);
            }
        });

        jTextAreaAdresse.setColumns(20);
        jTextAreaAdresse.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextAreaAdresse.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAdresse);

        jButtonAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/add_customer_hotel.png"))); // NOI18N
        jButtonAdd.setText("Ajouter");
        jButtonAdd.setPreferredSize(new java.awt.Dimension(170, 59));
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/cancel.png"))); // NOI18N
        jButtonCancel.setText("Annuler");
        jButtonCancel.setPreferredSize(new java.awt.Dimension(170, 59));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jTextFieldCP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCPKeyTyped(evt);
            }
        });

        jTextFieldVille.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldVilleKeyTyped(evt);
            }
        });

        jLabelDDN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDDN.setText("Date de naissance :");

        jDateChooserDDN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPrenom, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCP, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelVille, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelDDN, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAdresse, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNom, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelMainLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldPrénom, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldVille, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(70, 70, 70))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                                        .addComponent(jTextFieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(275, 275, 275))
                                    .addGroup(jPanelMainLayout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())))
                            .addGroup(jPanelMainLayout.createSequentialGroup()
                                .addComponent(jDateChooserDDN, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabelPays)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxPays, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabelNewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNewStudent)
                .addGap(37, 37, 37)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNom)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrenom)
                    .addComponent(jTextFieldPrénom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAdresse)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCP)
                    .addComponent(jTextFieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVille)
                    .addComponent(jTextFieldVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPays)
                    .addComponent(jComboBoxPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooserDDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDDN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        ArrayList<Client> listCli = daoCli.selectClients();
        
        if(verifText())
        {
            Client cli = new Client();
            cli.setCl_Nom(jTextFieldNom.getText());
            cli.setCl_Prénom(jTextFieldPrénom.getText());
            cli.setCl_Adresse(jTextAreaAdresse.getText());
            cli.setCl_CP(Integer.parseInt(jTextFieldCP.getText()));
            cli.setCl_Ville(jTextFieldVille.getText());
            cli.setCl_Pays((Pays)jComboBoxPays.getSelectedItem());
            cli.setCl_Naiss(jDateChooserDDN.getDate());
            
            boolean test = false;
            
            for(Client c : listCli)
            {
                if(c.equals(cli))
                {
                    test = true;
                }
            }
            
            boolean ajout = false;
            
            // Si le client n'existe pas dans la base de données
            if(!test)
            {
                ajout = daoCli.insertClient(cli);
            }
            
            if(!ajout)
            {
                JOptionPane.showMessageDialog(null, "Insertion d'un client impossible !", "Avertissement", JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Opération réussie !", "Avertissement", JOptionPane.INFORMATION_MESSAGE);
            }
            
            this.dispose();
        }
    }//GEN-LAST:event_jButtonAddActionPerformed
    
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jTextFieldNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomKeyTyped
        char c = evt.getKeyChar();

        if(Character.isLetter(c) || Character.isISOControl(c))
        {
            evt = evt;
        }
        else
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNomKeyTyped

    private void jTextFieldPrénomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrénomKeyTyped
        char c = evt.getKeyChar();

        if(Character.isLetter(c) || Character.isISOControl(c))
        {
            evt = evt;
        }
        else
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPrénomKeyTyped

    private void jTextFieldCPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCPKeyTyped
        // Uniquement les chiffres sont autorisés
        if(!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCPKeyTyped

    private void jTextFieldVilleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldVilleKeyTyped
        char c = evt.getKeyChar();

        if(Character.isLetter(c) || Character.isISOControl(c))
        {
            evt = evt;

        }
        else
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldVilleKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JComboBox jComboBoxPays;
    private com.toedter.calendar.JDateChooser jDateChooserDDN;
    private javax.swing.JLabel jLabelAdresse;
    private javax.swing.JLabel jLabelCP;
    private javax.swing.JLabel jLabelDDN;
    private javax.swing.JLabel jLabelNewStudent;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelPays;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JLabel jLabelVille;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaAdresse;
    private javax.swing.JTextField jTextFieldCP;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrénom;
    private javax.swing.JTextField jTextFieldVille;
    // End of variables declaration//GEN-END:variables
    private DAOClient daoCli = Factory.getDAOClient();
    private DAOPays daoPays = Factory.getDAOPays();
}