package presentation;

import dao.*;
import daoMySQL.*;
import factory.*;
import java.util.*;
import javax.swing.*;
import java.awt.*;
import java.text.*;
import transfertObject.*;

/**
 *
 * @author Philippe-K
 */

public class JDAjoutReservation extends JDialog
{ 
    /**
     * Creates new form JDInsertReservation
     */
    public JDAjoutReservation(Frame parent, String titre)
    {
        super(parent, titre, true);
        initComponents();
        fillComponents();
        getRootPane().setDefaultButton(jButtonAdd);
        setLocation(parent.getX() + parent.getWidth() / 3, parent.getY() + parent.getHeight() / 3);
        setVisible(true);
    }
    
    private void fillComponents()
    {
        // La table Client
        ArrayList<Client> listeClients = daoCli.selectClients();
        for(int i = 0; i < listeClients.size(); i++)
        {
            // Insertion des objets dans la comboBox,
            // Mais ils sont affichés grâce à leurs méthodes
            jComboBoxClient.addItem(listeClients.get(i));
        }
        
        // La table Chambre
        ArrayList<Chambre> listeChambres = daoCh.selectChambres();
        for(int j = 0; j < listeChambres.size(); j++)
        {
            jComboBoxChambre.addItem(listeChambres.get(j));
        }
        
        Date maDate = new Date();
        jDateChooserDateArrivée.setDate(maDate);
    }
    
    private boolean checkData()
    {
        if(jComboBoxClient.getSelectedIndex() == -1 && jComboBoxChambre.getSelectedIndex() == -1 
           || jDateChooserDateArrivée.getDate() != null && Integer.parseInt(jTextFieldNbPers.getText()) <= 0)
        {
            JOptionPane.showMessageDialog(null, "Un ou plusieurs champs est/sont vides!! Remplissez tous les champs s'il vous plaît!!");
            return false;
        }
        else
        {
            return true;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jLabelNewBook = new javax.swing.JLabel();
        jLabelNbPers = new javax.swing.JLabel();
        jLabelSelectClient = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabelDDN = new javax.swing.JLabel();
        jDateChooserDateArrivée = new com.toedter.calendar.JDateChooser();
        jLabelSelectChambre = new javax.swing.JLabel();
        jComboBoxClient = new javax.swing.JComboBox();
        jComboBoxChambre = new javax.swing.JComboBox();
        jTextFieldNbPers = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelMain.setBackground(new java.awt.Color(153, 204, 255));

        jLabelNewBook.setFont(new java.awt.Font("Cambria", 1, 28)); // NOI18N
        jLabelNewBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNewBook.setText("Ajouter une nouvelle réservation");
        jLabelNewBook.setFocusable(false);
        jLabelNewBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelNbPers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNbPers.setText("Nombre de personnes :");

        jLabelSelectClient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelSelectClient.setText("Sélectionner un client :");

        jButtonAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/save.png"))); // NOI18N
        jButtonAdd.setText("Enregistrer");
        jButtonAdd.setPreferredSize(new java.awt.Dimension(170, 59));
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/cancel.png"))); // NOI18N
        jButtonCancel.setText("Annuler");
        jButtonCancel.setPreferredSize(new java.awt.Dimension(170, 59));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabelDDN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDDN.setText("Date d'arrivée :");

        jDateChooserDateArrivée.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabelSelectChambre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelSelectChambre.setText("Sélectionner une chambre :");

        jTextFieldNbPers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNbPersKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNewBook, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelSelectClient)
                            .addComponent(jLabelSelectChambre)
                            .addComponent(jLabelDDN)
                            .addComponent(jLabelNbPers))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooserDateArrivée, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(jComboBoxClient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxChambre, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNbPers, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanelMainLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAdd, jButtonCancel});

        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNewBook)
                .addGap(49, 49, 49)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSelectClient)
                    .addComponent(jComboBoxClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSelectChambre)
                    .addComponent(jComboBoxChambre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooserDateArrivée, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDDN))
                .addGap(39, 39, 39)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNbPers)
                    .addComponent(jTextFieldNbPers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        if(checkData())
        {
            Reservation res = new Reservation();
            res.setCliRes((Client)jComboBoxClient.getSelectedItem());
            res.setChRes((Chambre)jComboBoxChambre.getSelectedItem());
            res.setPlRes(daoPlan.selectPlanning(jDateChooserDateArrivée.getDate()));
            res.setNbPers(Integer.parseInt(jTextFieldNbPers.getText()));
            
            boolean ajout = false;
            
            if(daoRes.isAvailable(res))
            {
                ajout = daoRes.insertReservation(res);
            }

            if(!ajout)
            {
                JOptionPane.showMessageDialog(null, "Insertion d'une réservation impossible !", "Avertissement", JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Opération réussie !", "Avertissement", JOptionPane.INFORMATION_MESSAGE);
            }
            
            this.dispose();
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jTextFieldNbPersKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNbPersKeyTyped
        // Uniquement les chiffres sont autorisés
        if(!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNbPersKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JComboBox jComboBoxChambre;
    private javax.swing.JComboBox jComboBoxClient;
    private com.toedter.calendar.JDateChooser jDateChooserDateArrivée;
    private javax.swing.JLabel jLabelDDN;
    private javax.swing.JLabel jLabelNbPers;
    private javax.swing.JLabel jLabelNewBook;
    private javax.swing.JLabel jLabelSelectChambre;
    private javax.swing.JLabel jLabelSelectClient;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JTextField jTextFieldNbPers;
    // End of variables declaration//GEN-END:variables
    private DAOChambre daoCh = Factory.getDAOChambre();
    private DAOClient daoCli = Factory.getDAOClient();
    private DAOPlanning daoPlan = Factory.getDAOPlanning();
    private DAOReservation daoRes = Factory.getDAOReservation();
}