package presentation;

import dao.*;
import daoMySQL.*;
import factory.*;
import java.util.*;
import javax.swing.*;
import java.awt.*;
import java.text.*;
import transfertObject.*;

/**
 *
 * @author Philippe-K
 */

public class JDModifReservation extends JDialog
{
    /**
     * Creates new form JDInsertReservation
     */
    public JDModifReservation(Frame parent, String titre, Reservation res)
    {
        super(parent, titre, true);
        initComponents();
        fillComponents(res);
        getRootPane().setDefaultButton(jButtonUpdate);
        setLocation(parent.getX() + parent.getWidth() / 3, parent.getY() + parent.getHeight() / 3);
        setVisible(true);
    }
    
    private void fillComponents(Reservation res)
    {
        jTextFieldIDRes.setText(String.valueOf(res.getResId()));
        
        // La table Client
        int numCli = res.getCliRes().getCl_Id();
        ArrayList<Client> cli = daoCli.selectClients();
        for(int i = 0; i < cli.size(); i++)
        {
            jComboBoxClient.addItem(cli.get(i));
            if(cli.get(i).getCl_Id() == numCli)
            {
                jComboBoxClient.setSelectedIndex(i);
            }
        }
        
        jComboBoxClient.setSelectedItem(res.getCliRes());
        
        // La table Chambre
        int numCh = res.getChRes().getCh_Num();
        ArrayList<Chambre> ch = daoCh.selectChambres();
        for(int j = 0; j < ch.size(); j++)
        {
            jComboBoxChambre.addItem(ch.get(j));
            if(ch.get(j).getCh_Num() == numCh)
            {
                jComboBoxChambre.setSelectedIndex(j);
            }
        }
        
        jComboBoxChambre.setSelectedItem(res.getChRes());
        
        jDateChooserDateArrivée.setDate(res.getPlRes().getPl_Date());
        
        jTextFieldNbPers.setText(String.valueOf(res.getNbPers()));
        
        allBooking = res;
    }
    
    private boolean checkData()
    {
        if(jComboBoxClient.getSelectedIndex() == -1 && jComboBoxChambre.getSelectedIndex() == -1 
           || jDateChooserDateArrivée.getDate() != null && Integer.parseInt(jTextFieldNbPers.getText()) <= 0)
        {
            JOptionPane.showMessageDialog(null, "Un ou plusieurs champs est/sont vides!! Remplissez tous les champs s'il vous plaît!!");
            return false;
        }
        else
        {
            return true;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jLabelNewBook = new javax.swing.JLabel();
        jLabelNbPers = new javax.swing.JLabel();
        jLabelSelectClient = new javax.swing.JLabel();
        jButtonUpdate = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabelDDN = new javax.swing.JLabel();
        jDateChooserDateArrivée = new com.toedter.calendar.JDateChooser();
        jLabelSelectChambre = new javax.swing.JLabel();
        jComboBoxClient = new javax.swing.JComboBox();
        jComboBoxChambre = new javax.swing.JComboBox();
        jTextFieldNbPers = new javax.swing.JTextField();
        jTextFieldIDRes = new javax.swing.JTextField();
        jLabelSelectClient1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelMain.setBackground(new java.awt.Color(153, 204, 255));

        jLabelNewBook.setFont(new java.awt.Font("Cambria", 1, 28)); // NOI18N
        jLabelNewBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNewBook.setText("Modifier une réservation sélectionnée");
        jLabelNewBook.setFocusable(false);
        jLabelNewBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelNbPers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNbPers.setText("Nombre de personnes :");

        jLabelSelectClient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelSelectClient.setText("Sélectionner un client :");

        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/save.png"))); // NOI18N
        jButtonUpdate.setText("Sauvegarder");
        jButtonUpdate.setPreferredSize(new java.awt.Dimension(170, 59));
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/cancel.png"))); // NOI18N
        jButtonCancel.setText("Annuler");
        jButtonCancel.setPreferredSize(new java.awt.Dimension(170, 59));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabelDDN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDDN.setText("Date d'arrivée :");

        jDateChooserDateArrivée.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabelSelectChambre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelSelectChambre.setText("Sélectionner une chambre :");

        jTextFieldNbPers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNbPersKeyTyped(evt);
            }
        });

        jTextFieldIDRes.setEnabled(false);

        jLabelSelectClient1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelSelectClient1.setText("idRes :");

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabelNewBook, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelSelectClient)
                            .addComponent(jLabelNbPers)
                            .addComponent(jLabelDDN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBoxClient, javax.swing.GroupLayout.Alignment.LEADING, 0, 227, Short.MAX_VALUE)
                            .addComponent(jTextFieldNbPers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserDateArrivée, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabelSelectChambre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxChambre, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabelSelectClient1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldIDRes, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanelMainLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancel, jButtonUpdate});

        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNewBook)
                .addGap(35, 35, 35)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIDRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSelectClient1))
                .addGap(33, 33, 33)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSelectClient)
                    .addComponent(jComboBoxClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSelectChambre)
                    .addComponent(jComboBoxChambre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooserDateArrivée, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDDN))
                .addGap(37, 37, 37)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNbPers)
                    .addComponent(jTextFieldNbPers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        if(checkData())
        {
            Reservation res = new Reservation();
            res.setResId(Integer.parseInt(jTextFieldIDRes.getText()));
            res.setCliRes((Client)jComboBoxClient.getSelectedItem());
            res.setChRes((Chambre)jComboBoxChambre.getSelectedItem());
            res.setPlRes(daoPlan.selectPlanning(jDateChooserDateArrivée.getDate()));
            res.setNbPers(Integer.parseInt(jTextFieldNbPers.getText()));
            boolean ajout = false;
            
            // Si la chambre et la date restent la même, alors on peut modifier la réservation
            if(daoRes.isAvailable(res) || allBooking.getChRes().getCh_Num() == res.getChRes().getCh_Num() && allBooking.getPlRes().getPl_Id() == res.getPlRes().getPl_Id())
            {
                ajout = daoRes.updateReservation(res);
            }

            if(!ajout)
            {
                JOptionPane.showMessageDialog(null, "Modification d'une réservation impossible !", "Avertissement", JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Réservation mise à jour avec succès!", "Avertissement", JOptionPane.INFORMATION_MESSAGE);
            }

            this.dispose();
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jTextFieldNbPersKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNbPersKeyTyped
        // Uniquement les chiffres sont autorisés
        if(!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNbPersKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox jComboBoxChambre;
    private javax.swing.JComboBox jComboBoxClient;
    private com.toedter.calendar.JDateChooser jDateChooserDateArrivée;
    private javax.swing.JLabel jLabelDDN;
    private javax.swing.JLabel jLabelNbPers;
    private javax.swing.JLabel jLabelNewBook;
    private javax.swing.JLabel jLabelSelectChambre;
    private javax.swing.JLabel jLabelSelectClient;
    private javax.swing.JLabel jLabelSelectClient1;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JTextField jTextFieldIDRes;
    private javax.swing.JTextField jTextFieldNbPers;
    // End of variables declaration//GEN-END:variables
    private DAOChambre daoCh = Factory.getDAOChambre();
    private DAOClient daoCli = Factory.getDAOClient();
    private DAOPlanning daoPlan = Factory.getDAOPlanning();
    private DAOReservation daoRes = Factory.getDAOReservation();
    Reservation allBooking = new Reservation();
}