package presentation;

import dao.*;
import daoMySQL.*;
import factory.*;
import javax.swing.*;
import java.awt.*;
import java.text.*;
import java.util.*;
import java.util.regex.*;
import transfertObject.*;

/**
 *
 * @author Philippe-K
 */

public class JDModifClient extends JDialog
{
    ImageIcon noIcon = new ImageIcon("no.png");
    
    /**
     * Creates new form JDInsertClient
     */
    public JDModifClient(Frame parent, String titre, Client cl)
    {
        super(parent, titre, true);
        initComponents();
        fillComponents(cl);
        getRootPane().setDefaultButton(jButtonUpdate);
        setLocation(parent.getX() + parent.getWidth() / 3, parent.getY() + parent.getHeight() / 3);
        setVisible(true);
    }
    
    private void fillComponents(Client cl)
    {
        jTextFieldID.setText(String.valueOf(cl.getCl_Id()));
        jTextFieldNom.setText(cl.getCl_Nom());
        jTextFieldPrénom.setText(cl.getCl_Prénom());
        jTextAreaAdresse.setText(cl.getCl_Adresse());
        jTextFieldCP.setText(String.valueOf(cl.getCl_CP()));
        jTextFieldVille.setText(cl.getCl_Ville());
        
        /* Charger toutes les pays */
        int numPays = cl.getCl_Pays().getP_Id();
        ArrayList<Pays> pays = daoPays.selectPays();
        for(int i = 0; i < pays.size(); i++)
        {
            jComboBoxPays.addItem(pays.get(i));
            if(pays.get(i).getP_Id() == numPays)
            {
                jComboBoxPays.setSelectedIndex(i);
            }
        }
        jComboBoxPays.setSelectedItem(cl.getCl_Pays());
        
        jDateChooserDDN.setDate(cl.getCl_Naiss());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jLabelNewStudent = new javax.swing.JLabel();
        jLabelPrenom = new javax.swing.JLabel();
        jLabelNom = new javax.swing.JLabel();
        jLabelAdresse = new javax.swing.JLabel();
        jLabelCP = new javax.swing.JLabel();
        jLabelVille = new javax.swing.JLabel();
        jLabelPays = new javax.swing.JLabel();
        jTextFieldPrénom = new javax.swing.JTextField();
        jTextFieldNom = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAdresse = new javax.swing.JTextArea();
        jButtonUpdate = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jTextFieldCP = new javax.swing.JTextField();
        jTextFieldVille = new javax.swing.JTextField();
        jComboBoxPays = new javax.swing.JComboBox();
        jLabelDDN = new javax.swing.JLabel();
        jDateChooserDDN = new com.toedter.calendar.JDateChooser();
        jTextFieldID = new javax.swing.JTextField();
        jLabelNom1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelMain.setBackground(new java.awt.Color(153, 204, 255));

        jLabelNewStudent.setFont(new java.awt.Font("Cambria", 1, 28)); // NOI18N
        jLabelNewStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNewStudent.setText("   Modifier le client sélectionné");
        jLabelNewStudent.setFocusable(false);
        jLabelNewStudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelPrenom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPrenom.setText("Prénom :");

        jLabelNom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNom.setText("Nom :");

        jLabelAdresse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelAdresse.setText("Adresse :");

        jLabelCP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCP.setText("Code postal :");

        jLabelVille.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelVille.setText("Ville :");

        jLabelPays.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPays.setText("Pays :");

        jTextFieldPrénom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrénomKeyTyped(evt);
            }
        });

        jTextFieldNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomKeyTyped(evt);
            }
        });

        jTextAreaAdresse.setColumns(20);
        jTextAreaAdresse.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextAreaAdresse.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAdresse);

        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/save.png"))); // NOI18N
        jButtonUpdate.setText("Sauvegarder");
        jButtonUpdate.setPreferredSize(new java.awt.Dimension(170, 59));
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/cancel.png"))); // NOI18N
        jButtonCancel.setText("Annuler");
        jButtonCancel.setPreferredSize(new java.awt.Dimension(170, 59));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jTextFieldCP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCPKeyTyped(evt);
            }
        });

        jTextFieldVille.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldVilleKeyTyped(evt);
            }
        });

        jLabelDDN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDDN.setText("Date de naissance :");

        jDateChooserDDN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldID.setEnabled(false);

        jLabelNom1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNom1.setText("idClient :");

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabelNewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                        .addGap(0, 41, Short.MAX_VALUE)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                                .addComponent(jLabelCP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(275, 275, 275))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNom1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelNom, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(70, 70, 70))
                            .addGroup(jPanelMainLayout.createSequentialGroup()
                                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelMainLayout.createSequentialGroup()
                                        .addComponent(jLabelVille)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldVille, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelMainLayout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addComponent(jLabelPrenom)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldPrénom, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelMainLayout.createSequentialGroup()
                                            .addGap(27, 27, 27)
                                            .addComponent(jLabelAdresse)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(70, 70, 70))))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDDN, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPays, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelMainLayout.createSequentialGroup()
                                .addComponent(jDateChooserDDN, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelMainLayout.createSequentialGroup()
                                .addComponent(jComboBoxPays, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );

        jPanelMainLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancel, jButtonUpdate});

        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNewStudent)
                .addGap(29, 29, 29)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNom1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNom)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrenom)
                    .addComponent(jTextFieldPrénom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAdresse)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCP)
                    .addComponent(jTextFieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVille)
                    .addComponent(jTextFieldVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPays)
                    .addComponent(jComboBoxPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooserDDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDDN))
                .addGap(26, 26, 26)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        ArrayList<Client> listCli = daoCli.selectClients();      
        if(verifText())
        {
            Client cli = new Client();
            cli.setCl_Id(Integer.parseInt(jTextFieldID.getText()));
            cli.setCl_Nom(jTextFieldNom.getText());
            cli.setCl_Prénom(jTextFieldPrénom.getText());
            cli.setCl_Adresse(jTextAreaAdresse.getText());
            cli.setCl_CP(Integer.parseInt(jTextFieldCP.getText()));
            cli.setCl_Ville(jTextFieldVille.getText());
            cli.setCl_Pays((Pays)jComboBoxPays.getSelectedItem());
            cli.setCl_Naiss(jDateChooserDDN.getDate());
            
            boolean test = false;
            for(Client c : listCli)
            {
                if(c.equals(cli))
                {
                    test = true;
                }
            }
            
            boolean ajout = false;
            
            if(!listCli.contains(cli))
            {
                ajout = daoCli.updateClient(cli);
            }
            
            if(!ajout)
            {
                JOptionPane.showMessageDialog(null, "Modification d'un client impossible !", "Avertissement", JOptionPane.ERROR_MESSAGE, noIcon);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Opération réussie !", "Avertissement", JOptionPane.INFORMATION_MESSAGE);
            }
            this.dispose();
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed
    
    private boolean verifText()
    {
        if(jTextFieldNom.getText().equals("") || jTextFieldPrénom.getText().equals("") 
           || jTextAreaAdresse.getText().equals("") || Integer.parseInt(jTextFieldCP.getText()) <= 0 
           || jTextFieldVille.getText().equals("") || jComboBoxPays.getSelectedIndex() == -1 || jDateChooserDDN.getDate() == null)
        {
            JOptionPane.showMessageDialog(null, "Un ou plusieurs champs est/sont vides!! Saisissez tous les champs s'il vous plaît!!", "Avertissement", JOptionPane.ERROR_MESSAGE, noIcon);
            return false;
        }
        else
        {
            return true;
        }
    }
    
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jTextFieldNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomKeyTyped
        char c = evt.getKeyChar();

        if(Character.isLetter(c) || Character.isISOControl(c))
        {
            evt = evt;
        }
        else
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNomKeyTyped

    private void jTextFieldPrénomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrénomKeyTyped
        char c = evt.getKeyChar();

        if(Character.isLetter(c) || Character.isISOControl(c))
        {
            evt = evt;
        }
        else
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPrénomKeyTyped

    private void jTextFieldCPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCPKeyTyped
        // Uniquement les chiffres sont autorisés
        if(!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCPKeyTyped

    private void jTextFieldVilleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldVilleKeyTyped
        char c = evt.getKeyChar();

        if(Character.isLetter(c) || Character.isISOControl(c))
        {
            evt = evt;

        }
        else
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldVilleKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox jComboBoxPays;
    private com.toedter.calendar.JDateChooser jDateChooserDDN;
    private javax.swing.JLabel jLabelAdresse;
    private javax.swing.JLabel jLabelCP;
    private javax.swing.JLabel jLabelDDN;
    private javax.swing.JLabel jLabelNewStudent;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelNom1;
    private javax.swing.JLabel jLabelPays;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JLabel jLabelVille;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaAdresse;
    private javax.swing.JTextField jTextFieldCP;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrénom;
    private javax.swing.JTextField jTextFieldVille;
    // End of variables declaration//GEN-END:variables
    private DAOClient daoCli = Factory.getDAOClient();
    private DAOPays daoPays = Factory.getDAOPays();
}