package presentation;

import factory.*;
import javax.swing.*;
import java.awt.*;
import java.util.logging.*;
import java.beans.*;

/**
 *
 * @author Philippe-K
 */

public class JFPrincipale extends JFrame
{
    /**
     * Creates new form JFPrincipale
     */
    public JFPrincipale()
    {
        initComponents();
        setLocation(400, 200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneMain = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBarMain = new javax.swing.JMenuBar();
        jMenuFichier = new javax.swing.JMenu();
        jMenuItemQuitter = new javax.swing.JMenuItem();
        jMenuEdition = new javax.swing.JMenu();
        jMenuItemClient = new javax.swing.JMenuItem();
        jMenuItemPays = new javax.swing.JMenuItem();
        jMenuItemChambre = new javax.swing.JMenuItem();
        jMenuItemPlanning = new javax.swing.JMenuItem();
        jMenuItemReservation = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/countryside.jpg"))); // NOI18N

        jDesktopPaneMain.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneMainLayout = new javax.swing.GroupLayout(jDesktopPaneMain);
        jDesktopPaneMain.setLayout(jDesktopPaneMainLayout);
        jDesktopPaneMainLayout.setHorizontalGroup(
            jDesktopPaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, Short.MAX_VALUE)
        );
        jDesktopPaneMainLayout.setVerticalGroup(
            jDesktopPaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 509, Short.MAX_VALUE)
        );

        jMenuFichier.setText("Fichier");

        jMenuItemQuitter.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemQuitter.setText("Quitter");
        jMenuItemQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuitterActionPerformed(evt);
            }
        });
        jMenuFichier.add(jMenuItemQuitter);

        jMenuBarMain.add(jMenuFichier);

        jMenuEdition.setText("Edition");

        jMenuItemClient.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemClient.setText("Client");
        jMenuItemClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClientActionPerformed(evt);
            }
        });
        jMenuEdition.add(jMenuItemClient);

        jMenuItemPays.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemPays.setText("Pays");
        jMenuItemPays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPaysActionPerformed(evt);
            }
        });
        jMenuEdition.add(jMenuItemPays);

        jMenuItemChambre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemChambre.setText("Chambre");
        jMenuItemChambre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemChambreActionPerformed(evt);
            }
        });
        jMenuEdition.add(jMenuItemChambre);

        jMenuItemPlanning.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemPlanning.setText("Planning");
        jMenuItemPlanning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPlanningActionPerformed(evt);
            }
        });
        jMenuEdition.add(jMenuItemPlanning);

        jMenuItemReservation.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemReservation.setText("Réservation");
        jMenuItemReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReservationActionPerformed(evt);
            }
        });
        jMenuEdition.add(jMenuItemReservation);

        jMenuBarMain.add(jMenuEdition);

        setJMenuBar(jMenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneMain)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClientActionPerformed
        // Cette méthode efface l'ancienne interface (DesktopPane) pour préparer la nouvelle interface
        jDesktopPaneMain.removeAll();
        
        // Création d'une nouvelle instance de la JInternalFrame
        JIFClients f = new JIFClients();
        
        // Ajout de l'instance dans le Desktop
        jDesktopPaneMain.add(f);
        try
        {
            f.setMaximum(true);
        }
        catch(PropertyVetoException e)
        {
            System.out.println("Problème de maximize");
        }
        jDesktopPaneMain.repaint();
    }//GEN-LAST:event_jMenuItemClientActionPerformed

    private void jMenuItemPaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPaysActionPerformed
        jDesktopPaneMain.removeAll();
        JIFPays f = new JIFPays();
        jDesktopPaneMain.add(f);
        try
        {
            f.setMaximum(true);
        }
        catch(PropertyVetoException e)
        {
            System.out.println("Problème de maximize");
        }
        jDesktopPaneMain.repaint();
    }//GEN-LAST:event_jMenuItemPaysActionPerformed

    private void jMenuItemChambreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemChambreActionPerformed
        jDesktopPaneMain.removeAll();
        JIFChambres f = new JIFChambres();
        jDesktopPaneMain.add(f);
        try
        {
            f.setMaximum(true);
        }
        catch(PropertyVetoException e)
        {
            System.out.println("Problème de maximize");
        }
        jDesktopPaneMain.repaint();
    }//GEN-LAST:event_jMenuItemChambreActionPerformed

    private void jMenuItemPlanningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPlanningActionPerformed
        jDesktopPaneMain.removeAll();
        JIFPlanning f = new JIFPlanning();
        jDesktopPaneMain.add(f);
        try
        {
            f.setMaximum(true);
        }
        catch(PropertyVetoException e)
        {
            System.out.println("Problème de maximize");
        }
        jDesktopPaneMain.repaint();
    }//GEN-LAST:event_jMenuItemPlanningActionPerformed

    private void jMenuItemReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReservationActionPerformed
        jDesktopPaneMain.removeAll();
        JIFReservations f = new JIFReservations();
        jDesktopPaneMain.add(f);
        try
        {
            f.setMaximum(true);
        }
        catch(PropertyVetoException e)
        {
            System.out.println("Problème de maximize");
        }
        jDesktopPaneMain.repaint();
    }//GEN-LAST:event_jMenuItemReservationActionPerformed

    private void jMenuItemQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuitterActionPerformed
        int rep = JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment quitter le programme ?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if(rep == JOptionPane.YES_OPTION)
        {
            Factory.getDAOConnexion().close();
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItemQuitterActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[])
//    {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try
//        {
//            for(UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels())
//            {
//                if("Nimbus".equals(info.getName()))
//                {
//                    UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        }
//        catch(ClassNotFoundException ex)
//        {
//            Logger.getLogger(JFPrincipale.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        catch(InstantiationException ex)
//        {
//            Logger.getLogger(JFPrincipale.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        catch(IllegalAccessException ex)
//        {
//            Logger.getLogger(JFPrincipale.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        catch(UnsupportedLookAndFeelException ex)
//        {
//            Logger.getLogger(JFPrincipale.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        EventQueue.invokeLater(new Runnable()
//        {
//            public void run()
//            {
//                new JFPrincipale().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPaneMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBarMain;
    private javax.swing.JMenu jMenuEdition;
    private javax.swing.JMenu jMenuFichier;
    private javax.swing.JMenuItem jMenuItemChambre;
    private javax.swing.JMenuItem jMenuItemClient;
    private javax.swing.JMenuItem jMenuItemPays;
    private javax.swing.JMenuItem jMenuItemPlanning;
    private javax.swing.JMenuItem jMenuItemQuitter;
    private javax.swing.JMenuItem jMenuItemReservation;
    // End of variables declaration//GEN-END:variables
}