package presentation;

import javax.swing.*;
import dao.*;
import factory.*;
import javax.swing.border.*;
import javax.swing.table.*;
import model.*;

/**
 *
 * @author Philippe-K
 */

public class JIFChambres extends JInternalFrame
{

    /**
     * Creates new form JIFChambres
     */
    public JIFChambres()
    {
        initComponents();
        setLocation(400, 200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jLabelNewChambre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCh = new JTable(myModel);
        ;

        setBorder(null);
        setTitle("Chambres");
        setVisible(true);

        jPanelMain.setBackground(new java.awt.Color(153, 204, 255));

        jLabelNewChambre.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabelNewChambre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNewChambre.setText("Gestion des chambres");
        jLabelNewChambre.setFocusable(false);
        jLabelNewChambre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        //taille automatique
        jTableCh.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

        //on centre les titres des colonnes
        DefaultTableCellRenderer custom = new DefaultTableCellRenderer(); 
        custom.setHorizontalAlignment(JLabel.CENTER);
        jTableCh.getTableHeader().setDefaultRenderer(custom);

        //on centre le texte
        for (int i = 0 ; i < jTableCh.getColumnCount(); i++){ 
            jTableCh.getColumnModel().getColumn(i).setCellRenderer(custom);
        }

        //Border sur le Header
        jTableCh.getTableHeader().setBorder(new EtchedBorder());

        //afficher les lignes verticales
        jTableCh.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTableCh);

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNewChambre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabelNewChambre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelNewChambre;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCh;
    // End of variables declaration//GEN-END:variables
    private DAOChambre daoCh = Factory.getDAOChambre();
    private TableModelChambres myModel = new TableModelChambres(daoCh.selectChambres());
}