package presentation;

import javax.swing.*;
import javax.swing.table.*;
import javax.swing.border.*;
import dao.*;
import factory.*;
import model.*;
import transfertObject.*;

/**
 *
 * @author Philippe-K
 */

public class JIFPlanning extends JInternalFrame
{
    /**
     * Creates new form JIFPlanning
     */
    public JIFPlanning()
    {
        initComponents();
        setLocation(400, 200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jLabelNewPlanning = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePlanning = new JTable(myModel);

        setBorder(null);
        setTitle("Planning");
        setVisible(true);

        jPanelMain.setBackground(new java.awt.Color(153, 204, 255));

        jLabelNewPlanning.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabelNewPlanning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNewPlanning.setText("Gestion du planning");
        jLabelNewPlanning.setFocusable(false);
        jLabelNewPlanning.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        //taille automatique
        jTablePlanning.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

        //on centre les titres des colonnes
        DefaultTableCellRenderer custom = new DefaultTableCellRenderer(); 
        custom.setHorizontalAlignment(JLabel.CENTER);
        jTablePlanning.getTableHeader().setDefaultRenderer(custom);

        //on centre le texte
        for(int i = 0; i < jTablePlanning.getColumnCount() ; i++){ 
            jTablePlanning.getColumnModel().getColumn(i).setCellRenderer(custom);
        }

        //Border sur le Header
        jTablePlanning.getTableHeader().setBorder(new EtchedBorder());

        //afficher les lignes verticales
        jTablePlanning.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTablePlanning);

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNewPlanning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabelNewPlanning, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelNewPlanning;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePlanning;
    // End of variables declaration//GEN-END:variables
    private DAOPlanning daoPlan = Factory.getDAOPlanning();
    private TableModelPlanning myModel = new TableModelPlanning(daoPlan.selectPlanning());
}