package presentation;

import factory.*;
import javax.swing.*;
import dao.*;
import model.*;

/**
 *
 * @author Philippe-K
 */

public class JIFPays extends JInternalFrame
{
    /**
     * Creates new form JIFPays
     */
    public JIFPays()
    {
        initComponents();
        setLocation(400, 200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jLabelNewPlanning = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPays = new javax.swing.JList<>();
        jLabelListe = new javax.swing.JLabel();

        setBorder(null);
        setTitle("Pays");
        setVisible(true);

        jPanelMain.setBackground(new java.awt.Color(153, 204, 255));

        jLabelNewPlanning.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabelNewPlanning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNewPlanning.setText("Gestion des pays");
        jLabelNewPlanning.setFocusable(false);
        jLabelNewPlanning.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jListPays.setModel(myModel);
        jScrollPane1.setViewportView(jListPays);

        jLabelListe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelListe.setText("Liste des pays :");

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabelNewPlanning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabelListe)
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabelNewPlanning, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabelListe)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelListe;
    private javax.swing.JLabel jLabelNewPlanning;
    private javax.swing.JList<String> jListPays;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private DAOPays daoPays= Factory.getDAOPays();;
    private ListModelPays myModel = new ListModelPays(daoPays.selectPays());
}